apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tvplayspider-test
  namespace: spiders
spec:
  schedule: "10 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tvplayspider-test
            image: registry-vpc.cn-hangzhou.aliyuncs.com/croton/playcountspider:latest
            env:
            - name: LOG_LEVEL
              value: ERROR
            envFrom:
            - secretRef:
                name: mysql-spider
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: registrysecret